services:
  vault:
    image: hashicorp/vault:1.17.6
    restart: unless-stopped
    networks:
      - backend
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: |
        storage "file" { path = "/vault/file" }
        listener "tcp" { address = "0.0.0.0:8200" tls_disable = "true" }
        api_addr = "http://127.0.0.1:8200"
        ui = true
    volumes:
      - ./data/vault/file:/vault/file
    command: server
